name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Fetching the code
        uses: actions/checkout@v2

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      
      - name: Create EC2 Key Pair file
        run: |
          echo "${{ secrets.EC2_KEY_PAIR }}" > keypair.pem
          chmod 600 keypair.pem
          cat keypair.pem

      - name: Set up Terraform Enviroment
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: terraform
        run: terraform init
      
      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -out=tfplan
      
      - name: Terraform Pull
        working-directory: terraform
        run: terraform state pull

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

          
          

      