name: React CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build:
    name: Deploy on Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  

      - name: Setup Node Enviroment
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Installing Dependiences
        run: npm install

      - name: Run ESLint
        run: npx eslint .
          

      - name: Build 
        run: npm run build --if-present

      - name: Running Test Case
        run: npm test

      - name: Archive Production Build
        uses: actions/upload-artifact@v4.3.3
        with:
          name: production-build
          path: build.zip
          overwrite: true
      
      
      
      
      
